//  
//  MyColors.Swift 
//  Generated by Lazy Cocoa 
// 
//  Created by User on 2015-03-02. 
//  Copyright (c) 2015 The Lazy Cocoa Project. All rights reserved. 
// 


import Foundation
import UIKit


extension UIFont { 

	
} 

extension UIColor { 

		/** 
			Color code: #F44336
		*/
		class func gmc_redColor() -> UIColor {
			return UIColor(red:0.957, green:0.263, blue:0.212, alpha:1.000)
		}
	
		/** 
			Color code: #E91E63
		*/
		class func gmc_pinkColor() -> UIColor {
			return UIColor(red:0.914, green:0.118, blue:0.388, alpha:1.000)
		}
	
		/** 
			Color code: #9C27B0
		*/
		class func gmc_purpleColor() -> UIColor {
			return UIColor(red:0.612, green:0.153, blue:0.690, alpha:1.000)
		}
	
		/** 
			Color code: #673AB7
		*/
		class func gmc_deepPurpleColor() -> UIColor {
			return UIColor(red:0.404, green:0.227, blue:0.718, alpha:1.000)
		}
	
		/** 
			Color code: #3F51B5
		*/
		class func gmc_indigoColor() -> UIColor {
			return UIColor(red:0.247, green:0.318, blue:0.710, alpha:1.000)
		}
	
		/** 
			Color code: #2196F3
		*/
		class func gmc_blueColor() -> UIColor {
			return UIColor(red:0.129, green:0.588, blue:0.953, alpha:1.000)
		}
	
		/** 
			Color code: #03A9F4
		*/
		class func gmc_lightBlueColor() -> UIColor {
			return UIColor(red:0.012, green:0.663, blue:0.957, alpha:1.000)
		}
	
		/** 
			Color code: #00BCD4
		*/
		class func gmc_cyanColor() -> UIColor {
			return UIColor(red:0.000, green:0.737, blue:0.831, alpha:1.000)
		}
	
		/** 
			Color code: #009688
		*/
		class func gmc_tealColor() -> UIColor {
			return UIColor(red:0.000, green:0.588, blue:0.533, alpha:1.000)
		}
	
		/** 
			Color code: #4CAF50
		*/
		class func gmc_greenColor() -> UIColor {
			return UIColor(red:0.298, green:0.686, blue:0.314, alpha:1.000)
		}
	
		/** 
			Color code: #8BC34A
		*/
		class func gmc_lightGreenColor() -> UIColor {
			return UIColor(red:0.545, green:0.765, blue:0.290, alpha:1.000)
		}
	
		/** 
			Color code: #CDDC39
		*/
		class func gmc_limeColor() -> UIColor {
			return UIColor(red:0.804, green:0.863, blue:0.224, alpha:1.000)
		}
	
		/** 
			Color code: #FFEB3B
		*/
		class func gmc_yellowColor() -> UIColor {
			return UIColor(red:1.000, green:0.922, blue:0.231, alpha:1.000)
		}
	
		/** 
			Color code: #FFC107
		*/
		class func gmc_amberColor() -> UIColor {
			return UIColor(red:1.000, green:0.757, blue:0.027, alpha:1.000)
		}
	
		/** 
			Color code: #FF9800
		*/
		class func gmc_orangeColor() -> UIColor {
			return UIColor(red:1.000, green:0.596, blue:0.000, alpha:1.000)
		}
	
		/** 
			Color code: #FF5722
		*/
		class func gmc_deepOrangeColor() -> UIColor {
			return UIColor(red:1.000, green:0.341, blue:0.133, alpha:1.000)
		}
	
		/** 
			Color code: #795548
		*/
		class func gmc_brownColor() -> UIColor {
			return UIColor(red:0.475, green:0.333, blue:0.282, alpha:1.000)
		}
	
		/** 
			Color code: #9E9E9E
		*/
		class func gmc_greyColor() -> UIColor {
			return UIColor(red:0.620, green:0.620, blue:0.620, alpha:1.000)
		}
	
		/** 
			Color code: #607D8B
		*/
		class func gmc_blueGreyColor() -> UIColor {
			return UIColor(red:0.376, green:0.490, blue:0.545, alpha:1.000)
		}
	
	
} 

