# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'BasicCells-Demo' do
  pod 'YZBasicCells'
  pod 'AFNetworking'
end

target 'BasicCells-DemoTests' do

end

